age_groups <- c("5-6 years", "7-8 years", "9-10 years")
photograph_A <- c(18, 2, 20)
photograph_B <- c(22, 28, 10)
photograph_C <- c(20, 40, 40)
cov_BC <- cov(photograph_B, photograph_C)
preferences <- matrix(c(photograph_A, photograph_B, photograph_C), nrow = 3)
cov_matrix <- cov(preferences)
cor_BC <- cor(photograph_B, photograph_C)
cor_matrix <- cor(preferences)
cat("\nSample Covariance between B and C:", cov_BC, "\n")
cat("\nSample Covariance Matrix for Preferences:\n", cov_matrix, "\n")
cat("\nSample Correlation between B and C:", cor_BC, "\n")
cat("\nSample Correlation Matrix for Preferences:\n", cor_matrix, "\n")